# Коммент
name: newautotest UI/API
# Это Название пайплаина
# ${{secrets.HARDCODEUSERPASSWD}}
# ${{vars.BACK_URL}}
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#ручной запуск 
  workflow_dispatch: 

jobs:
  homeworkPageObject:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.4.0
      - name: Установить пакет
        run: npm ci
      - name: Установить браузеры
        run: npx playwright install --with-deps
      - name: Setup AllureCTL
        uses:  allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: https://allure.qa.guru
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: ${{ vars.ALLURE_PROJECT_ID }}  
      - name: Запустить тесты
        run: npm t
        env: 
          BACK_URL_API: ${{vars.BACK_URL_API}}
          BACK_URL: ${{vars.BACK_URL}}
          
        #  Загружаем результаты в Allure TestOps
      - name: Upload results to Allure TestOps
        if: always()
        run: allurectl upload allure-results

        # 2. Получаем URL последнего запуска через API
      - name: Get latest launch URL
        id: launch_url
        if: always()
        run: |
          # Делаем запрос к API
          RESPONSE=$(curl -s -H "Authorization: Api-Token ${{ secrets.ALLURE_TOKEN }}" \
            "https://allure.qa.guru/api/rs/project/${{ vars.ALLURE_PROJECT_ID }}/launch?page=0&size=1&sort=createdDate,desc")
          
          # Достаем ID запуска. Оператор // empty предотвращает ошибки, если поля нет
          LAUNCH_ID=$(echo "$RESPONSE" | jq -r '.content[0].id // empty')
          
          # Формируем итоговую ссылку
          if [ -z "$LAUNCH_ID" ] || [ "$LAUNCH_ID" = "null" ]; then
            echo "Запуск не найден, используем ссылку на проект"
            LAUNCH_URL="https://allure.qa.guru/project/${{ vars.ALLURE_PROJECT_ID }}"
          else
            LAUNCH_URL="https://allure.qa.guru/launch/$LAUNCH_ID"
          fi
          
          # Сохраняем ссылку для следующих шагов
          echo "launch_url=$LAUNCH_URL" >> $GITHUB_OUTPUT
      
        
      - name: Генерируем отчет для телеграмм 
        if: always()
        run: npx allure-commandline generate allure-results -o allure-report --clean
        continue-on-error: true
        
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        continue-on-error: true
        if: always()
        with: 
          name: artefacts
          path: |
            allure-report/index.html
            allure-results
            playwright-report
            allure-report-single
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
       
      
      - name: Отправить уведомление в Telegram
        run: java "-DconfigFile=notification/telegram.json" -jar notification/allure-notifications-5.0.8.jar
        env:
           TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
           TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
           REPORT_URL: ${{steps.launch_url.outputs.launch_url}}
           BUILD_URL: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}
        
      
